name: Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.6
      - name: Install dependencies
        run: |
          sudo apt-get install libsndfile1-dev
	  sudo apt-get install ffmpeg
          pip install -e .
      - name: Test with pytest
        run: | 
          pytest -vv -p no:warnings  
